//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras
    {
        public long Id_compras { get; set; }
        public Nullable<long> num_serie { get; set; }
        public Nullable<System.DateTime> fecha_compra { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<long> id_e { get; set; }
        public Nullable<long> id_p { get; set; }
    }
}
