//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalles_ventas
    {
        public long id_detven { get; set; }
        public Nullable<long> cantidad { get; set; }
        public Nullable<double> precio_venta { get; set; }
        public Nullable<long> id_ventas { get; set; }
        public Nullable<long> id_producto { get; set; }
    }
}
