//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public long id_producto { get; set; }
        public string nombre { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<long> stock { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
