//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        public long id_ventas { get; set; }
        public Nullable<long> numero_serie { get; set; }
        public Nullable<System.DateTime> fecha_venta { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<long> id_c { get; set; }
        public Nullable<long> id_e { get; set; }
    }
}
